"""add consent flag

Revision ID: 68347a5650d2
Revises: 89cfa92d3805
Create Date: 2019-01-25 16:52:37.573866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68347a5650d2'
down_revision = '89cfa92d3805'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_info_event_ts', table_name='info_event')
    op.drop_table('info_event')
    op.add_column('user', sa.Column('consent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'consent')
    op.create_table('info_event',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('question_type', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('question_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('event_type', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('current_state', mysql.TEXT(), nullable=True),
    sa.Column('ts', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_info_event_ts', 'info_event', ['ts'], unique=False)
    # ### end Alembic commands ###

