"""init tables

Revision ID: 89cfa92d3805
Revises: 
Create Date: 2019-01-18 15:56:41.496887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cfa92d3805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=True),
    sa.Column('question_name', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_event_ts'), 'info_event', ['ts'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid_hash', sa.String(length=100), nullable=True),
    sa.Column('ts_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sid_hash'), 'user', ['sid_hash'], unique=True)
    op.create_index(op.f('ix_user_ts_created'), 'user', ['ts_created'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=True),
    sa.Column('question_name', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_ts'), 'event', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_ts'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_user_ts_created'), table_name='user')
    op.drop_index(op.f('ix_user_sid_hash'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_info_event_ts'), table_name='info_event')
    op.drop_table('info_event')
    # ### end Alembic commands ###

