"""Low Pri Events Table

Revision ID: dffc7dfb2eef
Revises: c795ee8630cd
Create Date: 2019-11-05 11:47:29.315476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffc7dfb2eef'
down_revision = 'c795ee8630cd'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lowprievents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=True),
    sa.Column('question_name', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lowprievents_ts'), 'lowprievents', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lowprievents_ts'), table_name='lowprievents')
    op.drop_table('lowprievents')
    # ### end Alembic commands ###

